### ISSUE TITLE
Rewrite editor

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4015]
Актуально для staging

## Priority 1

- [ ] При копировании списка с ссылками, в превью нарушено отображение, лишние пустые строки в Preview, до ссылки и после  https://github.com/Waiviogit/waivio/issues/4111#issuecomment-1217507735

## Priority 2

- [ ] Смайлом которые добавлены в едитор, тоже было бы неплохо добавить яркость как в модалке https://github.com/Waiviogit/waivio/issues/4015#issuecomment-1165421509
- [x] https://github.com/Waiviogit/waivio/issues/4092
- [x] https://github.com/Waiviogit/waivio/issues/4094
- [x] https://github.com/Waiviogit/waivio/issues/4118
- [x] https://github.com/Waiviogit/waivio/issues/4172
- [x] Кнопка очистки формата не срабатывает для цитаты https://github.com/Waiviogit/waivio/issues/4015#issuecomment-1200849679
- [x] https://github.com/Waiviogit/waivio/issues/4218

____________
Отложили (в других редакторах тоже так работает)
- [ ] Иногда при нажатии клавиши пробела - идет переход на новую строку (если текст копи-пейст с ссылками) https://github.com/Waiviogit/waivio/issues/4155#issuecomment-1225572327 https://github.com/Waiviogit/waivio/issues/4155

**Comment by Diana-Cherry-8** [comment]
Нотификации, что линки уже добавлены, после клика на Write review

https://user-images.githubusercontent.com/67378322/174313135-16b33059-3eb3-43ab-a094-3dfba32ec683.mp4

**Comment by Diana-Cherry-8** [comment]
Цвет placeholder write должен быть под цвет Title
![image](https://user-images.githubusercontent.com/67378322/174313764-b2b8e2df-9213-48ec-b1f5-22099d60aa82.png)

**Comment by Diana-Cherry-8** [comment]
После вставки текста, появляется нотификации о загрузки страницы
![image](https://user-images.githubusercontent.com/67378322/174314166-0862c047-743f-4173-bc02-10de027d4f09.png)

**Comment by Diana-Cherry-8** [comment]
После клика на едитор, курсор должен быть сразу в поле для text body
![image](https://user-images.githubusercontent.com/67378322/174315910-ff484b6f-b629-4726-b320-c4b00dc0f54a.png)

**Comment by Diana-Cherry-8** [comment]
Вставка картинки через ссылку не работает
![image](https://user-images.githubusercontent.com/67378322/174316428-4739b3bb-7ba9-40a2-adab-0b20dd1ea29f.png)

**Comment by Diana-Cherry-8** [comment]
drag and drop для картинок не работает

https://user-images.githubusercontent.com/67378322/174497463-00f22665-c562-4c5f-9698-bed8a0b98382.mp4

**Comment by Diana-Cherry-8** [comment]
При добавлении картинок, ту которую мы добаляем позже должна располагаться в посте ниже (то есть сначала добавили картинку 1, потом 2, и в посте ново добавлены располагаются ниже)
Сейчас, картинка, которая была позже добавлена, отображается выше (в самом начале поста)

![image](https://user-images.githubusercontent.com/67378322/174497540-f35d65b9-3720-4283-aa45-894ee608951d.png)
![image](https://user-images.githubusercontent.com/67378322/174497568-27f30182-8da7-454d-81a1-a2c3fd227e2f.png)

**Comment by Diana-Cherry-8** [comment]
Объекты не добавляются (через insert menu, через поле внизу)

https://user-images.githubusercontent.com/67378322/174497772-a3161666-fda7-4eb1-a68f-90efedceab58.mp4

**Comment by Diana-Cherry-8** [comment]
Картинка вставляется в самый вверх, а не в то место, где был курсор

https://user-images.githubusercontent.com/67378322/174616274-ca820f3b-2570-436f-ad94-394fc792b961.mp4

**Comment by Diana-Cherry-8** [comment]
> При добавлении картинок, ту которую мы добаляем позже должна располагаться в посте ниже (то есть сначала добавили картинку 1, потом 2, и в посте ново добавлены располагаются ниже) Сейчас, картинка, которая была позже добавлена, отображается выше (в самом начале поста)
> 
> ![image](https://user-images.githubusercontent.com/67378322/174497540-f35d65b9-3720-4283-aa45-894ee608951d.png) ![image](https://user-images.githubusercontent.com/67378322/174497568-27f30182-8da7-454d-81a1-a2c3fd227e2f.png)

Воспроизводиться 
Картинка, добелённая позже, должна быть ниже

**Comment by Diana-Cherry-8** [comment]
Pagination. В меню toolbar, отображать при 1м открытии: 5 элементов + кнопку Next, 
при следующей прокрутки: Back + 4 элемента + Next, и т.д.
чтобы у нас было стабильный размер toolbar
![image](https://user-images.githubusercontent.com/67378322/174620888-e5486b3a-9443-46e5-a310-deabb49f8544.png)

**Comment by Diana-Cherry-8** [comment]
После нажатия на вставку кода через insert menu, курсор должен быть сразу в поле кода
![image](https://user-images.githubusercontent.com/67378322/174624408-140d7069-715d-49d6-a5fd-e87e8db5661c.png)

**Comment by Diana-Cherry-8** [comment]
Если сначала ввести текст в body, а потом в title, кнопка ready to publish не активна (хотя все поля заполнены по факту)
![image](https://user-images.githubusercontent.com/67378322/174628287-e994ea6a-f859-4154-aa90-5399d13297c3.png)

**Comment by Diana-Cherry-8** [comment]
После вставки картинки, должна добавляться пустая строка, а после пустой строки - сразу отображаться курсор с кнопкой плюс
![image](https://user-images.githubusercontent.com/67378322/174629201-b60048ed-c095-4ea9-abc3-54dddc4ee65e.png)
![image](https://user-images.githubusercontent.com/67378322/174629264-a56d0bc0-8944-49ca-8f54-47fe96220ddc.png)

**Comment by Diana-Cherry-8** [comment]
После вставки линии, кнопка плюса должна быть возле курсора
![image](https://user-images.githubusercontent.com/67378322/174646567-006f7969-daac-4b73-8544-79ab593af372.png)

**Comment by Diana-Cherry-8** [comment]
Падает фронт если вставить ссылки скопированные с другого сайта
например https://www.shortpedia.com/en-in/technology-news/tiktok-reportedly-planning-expansion-into-ecommerce-space-in-the-us-market-1612812900

https://user-images.githubusercontent.com/67378322/174647179-176ae2b9-6a79-4535-8404-997764da6844.mp4

**Comment by Diana-Cherry-8** [comment]
Need to return quote button to toolbar https://github.com/Waiviogit/waivio/issues/3916

**Comment by Diana-Cherry-8** [comment]
падает фронт на мобилке, если текст сделать underline, а потом в слове рядом выбрать h3 или h4 

https://user-images.githubusercontent.com/67378322/174650647-10df089c-a28f-4aac-8d8f-e12916697b6d.mp4

**Comment by Diana-Cherry-8** [comment]
Смайли как будто приглушенны по цвету, яркости, может их по ярче можно сделать?
![image](https://user-images.githubusercontent.com/67378322/174654677-d1569661-85a0-42cb-97d4-ff445b1a3f58.png)

**Comment by Diana-Cherry-8** [comment]
После вставки видео, должна добавляться пустая строка, и после нее в новой строке курсор с кнопкой плюс
![image](https://user-images.githubusercontent.com/67378322/174741094-c7d2e62f-466a-4fbc-b044-5f25a4b870db.png)
![image](https://user-images.githubusercontent.com/67378322/174741398-add2ba19-26e2-4ef5-82ce-fea237dd9ae4.png)

**Comment by Diana-Cherry-8** [comment]
Если редактировать пост с пустыми строками и абзацами, то в едиторе текст будет отображаться как код
(daine-cherry, если нужно могу бросить кредо)

![image](https://user-images.githubusercontent.com/67378322/174746301-bece6c8d-2ce6-43d7-bb9f-52dbb1654eb1.png)
![image](https://user-images.githubusercontent.com/67378322/174746395-8e0d728b-49ae-478e-92f1-38628b97e6b0.png)

**Comment by Diana-Cherry-8** [comment]
При переключении draft, и загрузки черновика, нужно чтобы курсор с кнопкой плюс были уже в поле текста, в конце

https://user-images.githubusercontent.com/67378322/174749684-1a79a74a-d359-49a7-b528-7adf47d6d9a8.mp4

**Comment by Diana-Cherry-8** [comment]
Если в поле для вставки линки, написать waivio.com, то будет ссылка https://waiviodev.com/waivio.com, где waiviodev.com лишнее, должна быть обычная ссылки c https://{текст которые ввели в поле}
![image](https://user-images.githubusercontent.com/67378322/174753746-e8ffa4be-f926-4f43-b788-0cd5c89e7a69.png)
![image](https://user-images.githubusercontent.com/67378322/174753488-34e57f30-c8a0-405e-b412-0d620f892cd5.png)

**Comment by Diana-Cherry-8** [comment]
Курсор и плюсик пропадают, если ввести объект с решетки, и нажать курсором на объект (если объект выбрать с помощью клавиш (стрелочки и потом нажать Enter), то с курсором все в порядке)

https://user-images.githubusercontent.com/67378322/174966946-3806b8e3-74b3-46e5-8230-a37cc496229e.mp4

**Comment by Diana-Cherry-8** [comment]
При копировании кода, в preview могут появляться лишние обозначения пропадать пустые строки
https://www.programiz.com/javascript/examples/largest-number-three
Например, если копировать по строчно, то в превью есть лишние знаки, и сам вид кода пропал
![image](https://user-images.githubusercontent.com/67378322/174971249-5ae35b61-c06b-46e6-ab02-a95b85b650e3.png)
![image](https://user-images.githubusercontent.com/67378322/174971372-b11a7c83-39c4-4d67-8a19-1e985e4109bf.png)

А если скопировать весь код сразу, с кнопки, то пустые строки не отображаются
![image](https://user-images.githubusercontent.com/67378322/174971638-4331f8b2-c107-4f1d-aacc-253a79cef822.png)
![image](https://user-images.githubusercontent.com/67378322/174971843-bfb919f2-b033-4470-9c13-6c23c3d80f16.png)

**Comment by Diana-Cherry-8** [comment]
Лишние символы у кода в превью отображаются
![image](https://user-images.githubusercontent.com/67378322/174972750-234d25f0-4c33-4304-bf85-116a2fc0339b.png)
![image](https://user-images.githubusercontent.com/67378322/174972853-bad6d54e-b4ad-4ee9-8c73-368b6ff69632.png)

**Comment by Diana-Cherry-8** [comment]
Все отступы теряются, в опубликованном посте с кодом
![image](https://user-images.githubusercontent.com/67378322/174973145-646e62c1-8cd8-40b7-81dc-4a8ab619deb7.png)

**Comment by Diana-Cherry-8** [comment]
Знак italic, в toolbar должен быть с наклоном небольшим, сейчас он ровный
![image](https://user-images.githubusercontent.com/67378322/174973810-8d582e0b-3909-427e-83c3-54df5a7f6d72.png)
![image](https://user-images.githubusercontent.com/67378322/174974014-4f552ed8-bf9f-43d8-a9c7-40ee353720a3.png)

**Comment by Diana-Cherry-8** [comment]
Нет возможности искать через решетку если два слова (там раньше вроде была логика, что если один пробел после первого слова то мы не закрываем поле для поиска, а продолжаем, а если пробел уже после второго слова, то поле закрывалось, то есть поиск в два слова возможен)
![image](https://user-images.githubusercontent.com/67378322/174980670-a5eb27c7-e543-4eb7-9846-3dd0db9d8d2a.png)

![image](https://user-images.githubusercontent.com/67378322/174980545-44e111be-83d9-4ddd-a2f5-956f530849e2.png)

**Comment by Diana-Cherry-8** [comment]
Кнопка плюс не возвращается, если добавить объект через нижнее поле, а потом поставить курсор в поле для текста

https://user-images.githubusercontent.com/67378322/174985019-178823b2-43ac-4646-bdaf-ddcc46040d5c.mp4

**Comment by Diana-Cherry-8** [comment]
Нет выхода по пробелу с inline кода. 
Полностью поле не убирается с inline кода, если это было 1е слово 

https://user-images.githubusercontent.com/67378322/175016952-78c5f954-c89d-4bce-98f2-8ec34ee3ea9c.mp4


https://user-images.githubusercontent.com/67378322/175016960-dbc324ed-aca8-4543-b5dc-303c83101e9b.mp4

прод
https://user-images.githubusercontent.com/67378322/175017112-1f3c078c-a612-4273-8dc0-09e91ca8098f.mp4

**Comment by Diana-Cherry-8** [comment]
Падает фронт если нажать на Edit на типе page (у нас там тоже едитор)
https://waiviodev.com/object/pix-2nqjnb-test/page

https://user-images.githubusercontent.com/67378322/175019693-8e983a00-b2a5-4de1-8289-af7978b6b65d.mp4

![image](https://user-images.githubusercontent.com/67378322/175019857-fa27368c-c674-4a95-9707-45d346d06d51.png)

**Comment by Diana-Cherry-8** [comment]
Вставка текста с page 
https://waiviodev.com/object/ylr-waivio/page#mwt-about-waivio
После картинки кусок текста не добавился
![image](https://user-images.githubusercontent.com/67378322/175044194-72cdd148-f2cb-4247-a653-accc36e5d441.png)

И вторая картинка не отобразилась, текст тоже потерян (или переместился), нумерованный список стал обычным списком 
![image](https://user-images.githubusercontent.com/67378322/175044627-fbbad105-42cb-47c5-9329-c28d7f0f0711.png)

**Comment by Diana-Cherry-8** [comment]
при reload редактора теряются путые строки
https://github.com/Waiviogit/waivio/issues/4049

**Comment by Diana-Cherry-8** [comment]
text copy/paste not working (Edge browser) #4050

**Comment by Diana-Cherry-8** [comment]
Смайлом которые добавлены в едитор, тоже было бы неплохо добавить яркость как в модалке
![image](https://user-images.githubusercontent.com/67378322/175514009-3ebc50cf-22ae-479e-bdbc-0253b8664879.png)

**Comment by Diana-Cherry-8** [comment]
После добавления объекта пустые строки пропадают

https://user-images.githubusercontent.com/67378322/175515923-b560c134-8008-424c-be48-5e3aa4570b8c.mp4

**Comment by Diana-Cherry-8** [comment]
Если текст был сделан заголовком H1, H2, H3, H4, то кнопка удаления стилей не убирает это
![image](https://user-images.githubusercontent.com/67378322/175004780-5351e901-9363-4c10-aa11-613a8bb51aa7.png)

**Comment by Diana-Cherry-8** [comment]
поиск от решетки перекрывает текст

![image](https://user-images.githubusercontent.com/67378322/175774253-70547644-656b-4000-997b-c1a89c57bffe.png)

**Comment by Diana-Cherry-8** [comment]
После добавления объекта (с любого места - решетка, объект) - добавляется дополнительная пустая строка) 
![image](https://user-images.githubusercontent.com/67378322/175774265-a44934d7-58e2-4f93-b75a-e4f3e9fbbd0b.png)

**Comment by Diana-Cherry-8** [comment]
Дублирую коммент, с text copy/paste not working (Edge browser)
https://github.com/Waiviogit/waivio/issues/4050#issuecomment-1166289007

**Comment by Diana-Cherry-8** [comment]
Если добавить объект через решетку, потом его убрать (выключить карточку, удалить с едитора), и добавить еще раз, то карточка внизу не отобразиться 
https://user-images.githubusercontent.com/67378322/175919063-ab113cd0-7091-4216-bb7f-480eda4083ef.mp4

**Comment by Diana-Cherry-8** [comment]
После вставки объекта через #, пропадают карточки внизу (не всегда воспроизводиться)
например, у daine-cherry аккаунт черновие Google trains 8.4 Million MSMEs in Asia-Pacific region, helps app makers in India

https://user-images.githubusercontent.com/67378322/176170374-b71a50a5-2239-4571-a642-b1401b3555eb.mp4

**Comment by Diana-Cherry-8** [comment]
Идеальные вариант по курсору для вставленных объектов через решетку или insert menu - чтобы курсор становился через пробел сразу после объекта.
В если добавлять через нижнее поле (Attach hashtags, objects, pages, etc.), то курсор должен оставаться в поле
![image](https://user-images.githubusercontent.com/67378322/176181143-48288804-b9f5-4cb0-a608-0f3fca9e3397.png)
![image](https://user-images.githubusercontent.com/67378322/176181851-5c4e0c3c-484d-42fa-a447-99df271c4ac7.png)

**Comment by Diana-Cherry-8** [comment]
Название-линк для объекта не добавляется в сам едитор, после добавления с insert menu или нижнего поля.
Если подряд добавить объект с нижнего поля -> c insert menu -> решетку, то объект с решетки уберет предыдущее объекты
![image](https://user-images.githubusercontent.com/67378322/176430031-1f088c44-c7ff-4e70-973e-844797339e8c.png)


https://user-images.githubusercontent.com/67378322/176429802-fdfcef80-35cf-4e96-9f09-692545292925.mp4

**Comment by Diana-Cherry-8** [comment]
Поиск по решетке на два слова не работает
![image](https://user-images.githubusercontent.com/67378322/176431061-7f749d74-9500-4f42-b4c5-245326760de0.png)

**Comment by Diana-Cherry-8** [comment]
Поле для вставки ссылки, сохраняет предыдущую информацию

https://user-images.githubusercontent.com/67378322/176459079-b3a978b2-6932-438c-a404-5d852f7753ae.mp4

**Comment by Diana-Cherry-8** [comment]
На проде у daine-cherry в едиторе в черновике 6 Places On Earth Where Sun Never Sets, draft=null в ссылке если поклацать по черновикам в правом сайдбаре, и черновики отображаются больше чем 4

https://user-images.githubusercontent.com/67378322/176483541-b733e5f9-bae9-4634-b675-daef965d880a.mp4

**Comment by Diana-Cherry-8** [comment]
При копирование текста с ссылками - ссылки добавились в конец поста в едиторе
https://www.waivio.com/@waiviolabs/product-ratings-simplified-by-waivio
![image](https://user-images.githubusercontent.com/67378322/177111233-5e24b41d-5638-4c0b-bb60-1aba3cea6b08.png)

**Comment by Diana-Cherry-8** [comment]
Fix для цитаты, нет выхода из цитаты - по идеи, если два раза нажать ентер то должен быть выход (1й раз - новая строка, 2й - выход)

![image](https://user-images.githubusercontent.com/67378322/177118081-95829f0b-dbb1-486a-be80-5aae4eaa814e.png)

**Comment by Diana-Cherry-8** [comment]
Отступы теряются в опубликованном посте с кодом (click on insert menu -> click Code -> вставить скопированный код с сайта)
https://waiviodev.com/@daine-cherry/javascript-program-to-print-all-prime-numbers-in-an-interval
![image](https://user-images.githubusercontent.com/67378322/177279333-61c75eeb-9644-455d-bdb0-00f073a55e96.png)

**Comment by Diana-Cherry-8** [comment]
Вставка кода пары строк, одной строки, через insert menu, убирает саму область для кода, вставляется как обычный текст

https://user-images.githubusercontent.com/67378322/177281781-e4c06001-1916-4670-b443-c75cb17a0547.mp4

**Comment by Diana-Cherry-8** [comment]
В превью теряются стили текста, при копи-пейст 
https://www.waivio.com/object/ylr-waivio/page#mwt-about-waivio

https://user-images.githubusercontent.com/67378322/177553830-6c260f1b-4025-414e-a63e-ada7b5bfdfcc.mp4

![image](https://user-images.githubusercontent.com/67378322/177553934-1f3003e3-13e8-4f5d-a6ad-82260ff95e1e.png)
![image](https://user-images.githubusercontent.com/67378322/177554000-6240f6a0-e18a-4161-9b26-713f2cb349e4.png)

**Comment by Diana-Cherry-8** [comment]
При переключении черновиков их содержание меняется местами или может открываться пустым

https://user-images.githubusercontent.com/67378322/177720302-bd60f3e3-15a1-41b8-8180-92d73c53b417.mp4

**Comment by Diana-Cherry-8** [comment]
Стиль текста поменялся, и вторая строка сместилась, если скопировать текст с тайтлом
https://www.waivio.com/@waiviolabs/product-ratings-simplified-by-waivio
![image](https://user-images.githubusercontent.com/67378322/178207058-466cbdab-93cf-47ba-98f8-d4d9d36465e0.png)
![image](https://user-images.githubusercontent.com/67378322/178207096-a00cef0e-62b7-41f3-a2b0-ef6f7135c71d.png)

**Comment by Diana-Cherry-8** [comment]
Если написать в едиторе много слов и выделить его underline, потом открыть это черновик заново, то текст отображается в столбец с лишними тегами

https://user-images.githubusercontent.com/67378322/180159424-c99f3775-8c3d-4623-a5e2-70cb6cc668c6.mp4

**Comment by Diana-Cherry-8** [comment]
Заменить иконку для clear format
![clear-style-svgrepo-com (1)](https://user-images.githubusercontent.com/67378322/180956654-78dd6808-dde9-4ffc-be34-3270de1c5330.svg)

```
<svg width="24px" height="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
  <path d="M13,14.4142136 L13,20 L15,20 L15,22 L9,22 L9,20 L11,20 L11,12.4142136 L4.57580249,5.99001605 L3,5.95292783 L3,4.41421356 L1.29289322,2.70710678 L2.70710678,1.29289322 L22.7071068,21.2928932 L21.2928932,22.7071068 L13,14.4142136 Z M13,8.78578649 L11,6.78578649 L11,4 L8.21421351,4 L6.21421351,2 L21,2 L21,6 L19,5.95292783 L19,4 L13,4 L13,8.78578649 Z"/>
</svg>
```

**Comment by Diana-Cherry-8** [comment]
Кнопка очистки формата не срабатывает для цитаты

https://user-images.githubusercontent.com/67378322/182101087-9cb20b62-919d-47f9-939d-6949494c54e4.mp4

**Comment by Diana-Cherry-8** [comment]
Подравнять верхний отступ у тайтла в редакторе, чтобы в превью и редакторе отображалось одинаково

![image](https://user-images.githubusercontent.com/67378322/182103390-d5e76129-c65c-4e16-9ae5-4e1ec72b3053.png)
![image](https://user-images.githubusercontent.com/67378322/182103466-fa7bc034-e6e5-4628-b8d3-46ccea0cce33.png)

**Comment by Diana-Cherry-8** [comment]
Картинка отображается как ссылка в режиме модального поста и фул-скрина (в фиде отображается)
https://waiviodev.com/@ctrl-news/review-el-furniture-warehouse-perogies-rgcf8s

![image](https://user-images.githubusercontent.com/67378322/183625717-57700ed0-8321-4307-bd2f-4eb7cd84477e.png)
![image](https://user-images.githubusercontent.com/67378322/183625756-d0851883-12c1-4a8e-9348-5dfce39a506e.png)

**Comment by Diana-Cherry-8** [comment]
Теряются отступы и пустые строки, если скопировать текст со страницы https://www.waivio.com/object/mwt-about-waivio/page , вставить в едитор, и обновить страницу 

https://user-images.githubusercontent.com/67378322/185054824-02083c92-4691-44e6-b51e-c83047ff97d2.mp4

**Comment by Diana-Cherry-8** [comment]
Лишние символы в линке, если добавить линку в идитор, копировать, зайти в едитор снова и вставить

https://user-images.githubusercontent.com/67378322/186405256-6046b3fc-cfc7-453c-8919-7a6ecdb96845.mp4

**Comment by Diana-Cherry-8** [comment]
Copy link:
- toolbar с ссылкой открывать не нужно при выделении текста (чтобы адрес ссылка не копировалась в название);
- toolbar должен открываться при hover на название линки, и при нажатии на название линки (сейчас так и работает);
![image](https://user-images.githubusercontent.com/67378322/187146232-57804f55-483e-42fb-b5ca-75bdf8e4c783.png)

**Comment by Diana-Cherry-8** [comment]
При выделении нескольких ссылок, адрес ссылки одной из них, скопируется и добавиться в название.
При выделении всего текста (Ctrl + A), то название ссылок скопируется с адресом, и добавиться пустая строка между строками
 

https://user-images.githubusercontent.com/67378322/187214885-e8073c44-e034-435f-b462-637a12d1e10c.mp4

**Comment by Diana-Cherry-8** [comment]
Добавляется пустая строка перед ссылкой, если будет скопировать текст побольше

https://user-images.githubusercontent.com/67378322/187243591-08e98e72-44c8-4c02-9413-c5684b1f7259.mp4
