### ISSUE TITLE
Change editor in comments section on new one

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4024]
## Priority 1

- [x] #4231 
- [ ] Поле для вставки линки не всегда отображается полностью (в режиме модального окна, фул-скрина) #4230 https://github.com/Waiviogit/waivio/issues/4024#issuecomment-1190295011
- [x] Поле для вставки видео отображается не полностью в режиме мольного окна поста https://github.com/Waiviogit/waivio/issues/4024#issuecomment-1190298502

## Priority 2

- [x] После нажатия на кнопку для публикации комментария, кнопка плюс остается https://github.com/Waiviogit/waivio/issues/4024#issuecomment-1188974188
- [x] На темной теме поле белое и не видно текста в режиме модального окна, и фул-скрина
https://github.com/Waiviogit/waivio/issues/4024#issuecomment-1190110760
- [x] Поле для написания комментариев, увеличивается после нажатия на пост-title https://github.com/Waiviogit/waivio/issues/4024#issuecomment-1238033318

**Comment by Diana-Cherry-8** [comment]
Курсор мышки в виде загрузки при наведении в поле для комментариев, в режиме модального окна и фул-скрина поста

https://user-images.githubusercontent.com/67378322/179738905-6ef304d0-f0c5-4a8a-9d6c-1caecc656b75.mp4

**Comment by Diana-Cherry-8** [comment]
На странице объектов, на вкладке Updates, если нажать на кнопку для комментариев, то комментарии не отображаются, если отправить сообщение, то оно выглядит так как будто оно не отправилось (текст остается в поле)

https://user-images.githubusercontent.com/67378322/179742470-09e6fc00-2a7c-4697-a17c-354ee95c62a3.mp4

**Comment by Diana-Cherry-8** [comment]
На page, для Photo ломанная картинка в insert menu
https://waiviodev.com/object/ptj-test-page-id19071451/page
![image](https://user-images.githubusercontent.com/67378322/179743764-4091f293-37ce-486b-901d-44415fc82a62.png)

**Comment by Diana-Cherry-8** [comment]
Лишний символ в опубликованом комментарии, если добавить хештег

![image](https://user-images.githubusercontent.com/67378322/179746166-5b84d0d7-fac5-4234-9713-758af5bebf00.png)

https://user-images.githubusercontent.com/67378322/179746089-8a62a0d3-96fa-4c41-a0cf-26509217a988.mp4

**Comment by Diana-Cherry-8** [comment]
На темной теме поле белое и не видно текста в режиме модального окна, и фул-скрина
![image](https://user-images.githubusercontent.com/67378322/179961645-b64ebe8c-f413-4789-a31e-f5abc58ec58c.png)
![image](https://user-images.githubusercontent.com/67378322/179961715-c267196c-5dc4-4cac-a035-63c0c86dd5d7.png)

**Comment by Diana-Cherry-8** [comment]
Добавить новый едитор для комментариев в фиде

![image](https://user-images.githubusercontent.com/67378322/182101506-bd646c36-0848-4dc6-853f-73dd686d400a.png)

**Comment by Diana-Cherry-8** [comment]
#4231

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
