### ISSUE TITLE
Check rewards waiv

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4242]
# Staging

- [ ] Было бы хорошо, если бы после деактивации кампания сразу появлялась в нижней таблице (она с верхней пропадает, и только после перезагрузки отображается) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1164034054
- [x] Если пытаться активировать кампанию у которой дата не правильная, то нотификация будет просто крестик
https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1171048769
- [x] Валидация для экспертизы срабатывает на 3 целых числа https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1175840442
- [x] Registered upvoting accounts не отображается https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1179997656
- [x] Модалка не закрывает после нажатия на Reserved https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1180535904
- [x] Количество необходимых фото всегда 2 в модалке резервации, хотя при создании кампании там другое число
https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1195176128
- [x] Ссылка на primary объект введет на обычную ссылку, а не на defaultshowlink, в модалке для резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1195184448
- [x] Fix Reservation post https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1195200138
- [x] В Create отображается ошибка "Campaign could not be created. Your balance should be more than zero."
Хотя у пользователя есть waiv баланс (user - test.waivio) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1201000432
- [x] Fix ui для фильтров https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1205171364
- [x] Фильтр не работает на станице с secondary объектами (если на один объект два разных спонсора) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1205314057
- [x] Ссылки на объекты в модалке резервации с лишним object, не открывает нужные объекты https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1206153401
- [x] https://github.com/Waiviogit/waivio/issues/4224
- [x] https://github.com/Waiviogit/waivio/issues/4223
- [x] В Manage, в колонке Reserved много цифр после точки (максимум 8 должно быть) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1207940936
- [x] В Manage, в колонке Remaning, где активные кампании, много цифр после точки (new-way) (тут вроде только целый числа должны быть) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1207953628
- [x] Если добавить матчбота, то кампания не создастся error: "Bad Request" - "each value in matchBots must be a string"
Отправляется ненужная информация, должно только аккаунты отправлять (как на hive) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1208121426
- [x] Открывается Eligible, а не Reserved, если у пользователя есть зарезервированная кампания https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1208125305
- [x] Ссылки на объекты в посте о резервации не переходят, и отображаются со знаком ссылки https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1208133932
- [x] Fix к посту о резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1208142091
- [x] Fix к модалке резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1208154995
- [x] В посте о резервации кампании сумма отображается неправильная (больше похоже на курс hive) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1208187345
- [x] На карточке резервации Your Earn должен отображаться в waiv валюте https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1208193937
- [x] Промежуточно мегают красные пункты требований, при открытии модалки для резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1208216802
- [x] Фильтры на странице секондари объектов отображают больше объектов чем было до выбора фильтра, и продолжает отображаться одна карточка другого пользователя https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209234311
- [x] При переходе на секондари страницу с выбранным фильтром, фильтр должен оставаться (и показывать секондари объекты выбранного спонсора) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209242304
- [x] Карточки пользователей добавляются впритык в Registered upvoting accounts в Create https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209281771
- [x] Модалка резервации автоматически не закрывается после резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209292312

# Prod

**Comment by Diana-Cherry-8** [comment]
9.08 

### Manage tab

- [ ] Было бы хорошо, если бы после деактивации кампания сразу появлялась в нижней таблице (она с верхней пропадает, и только после перезагрузки отображается) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1164034054
- [ ] Если пытаться активировать кампанию у которой дата не правильная, то нотификация будет просто крестик
https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1171048769
- [x] В Manage, в колонке Remaning, где активные кампании, много цифр после точки (new-way) (тут вроде только целый числа должны быть) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1207953628

### Create tab
- [ ] В Create отображается ошибка "Campaign could not be created. Your balance should be more than zero."
Хотя у пользователя есть waiv баланс (user - test.waivio) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1201000432
- [ ] Карточки пользователей добавляются впритык в Registered upvoting accounts в Create https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209281771

### Eligible tab
- [ ] Фильтры на странице секондари объектов отображают больше объектов чем было до выбора фильтра, и продолжает отображаться одна карточка другого пользователя 

#### Reservation modal window
- [ ] Модалка резервации автоматически не закрывается после резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209292312
- [ ] Fix имя у дополнительного Legal документа, чтобы отображать обычное имя объекта (как Terms and Conditionals), а не permlink https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209357020
- [ ] https://github.com/Waiviogit/waivio/issues/4224


### Reservation post

- [ ]  Fix к посту о резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209292312

### Reserved tab

- [ ] Вознаграждение в waiv неправильное, должно быть равняться 1 USD в примере, в карточке Reserved.
Должны быть одинаковые значения в посте о резервации и на карточке reserved https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209333526

### Open tabs
- [ ] Вкладки иногда открываются неправильно после резервации и release, такое впечатление что пока не почистишь кеш, они будет продолжать отображать Eligible, хотя есть зарезервированная кампания, или Reserved, хотя кампания была релизнута https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209347820

**Comment by Diana-Cherry-8** [comment]
- [x] Была кампания с 2 секондари объекта, когда пользователь зарезервировал один объект, потом перешел в All на тот же primary объект, то у обоих объектов отображается карточка с кнопкой Write review https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1210584718

**Comment by Diana-Cherry-8** [comment]
**Back-task** https://github.com/Waiviogit/waivio/issues/3429

### Manage tab

- [ ] Было бы хорошо, если бы после деактивации кампания сразу появлялась в нижней таблице (она с верхней пропадает, и только после перезагрузки отображается) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1164034054
- [x] Если пытаться активировать кампанию у которой дата не правильная, то нотификация будет просто крестик
https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1171048769


### Create tab
- [x] В Create отображается ошибка "Campaign could not be created. Your balance should be more than zero."
Хотя у пользователя есть waiv баланс (user - test.waivio) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1201000432
- [x] countReservationDays (countReservationDays) если ввести число, то кампания не создастся, отправляется не число, а стринга https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1210549804


### Eligible tab


#### Reservation modal window

- [ ] Fix имя у дополнительного Legal документа, чтобы отображать обычное имя объекта (как Terms and Conditionals), а не permlink https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209357020
- [x] https://github.com/Waiviogit/waivio/issues/4224


### Reservation post

- [x] Fix ссылки объектов в 1 абзаце в посте о резервации, страница не открывается полностью.
Отображается иконки ссылки https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1210539845

### Reserved tab


- [ ]  После released, можно оставлять на Reserved, даже если она будет пустая https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209499474





### Release comment

- [x] Fix ссылку объекта в release комментарии открывает ломаную ссылку спонсора https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1210534309

### Other
- [ ] Вкладки иногда открываются неправильно после резервации и release, такое впечатление что пока не почистишь кеш, они будет продолжать отображать Eligible, хотя есть зарезервированная кампания, или Reserved, хотя кампания была релизнута https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209347820
- [x] Была кампания с 2 секондари объекта, когда пользователь зарезервировал один объект, потом перешел в All на тот же primary объект, то у обоих объектов отображается карточка с кнопкой Write review https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1210584718
- [x] https://github.com/Waiviogit/waivio/issues/4224

**Comment by Diana-Cherry-8** [comment]
**Back-task** https://github.com/Waiviogit/waivio/issues/3429

### Manage tab

- [ ] Было бы хорошо, если бы после деактивации кампания сразу появлялась в нижней таблице (она с верхней пропадает, и только после перезагрузки отображается) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1164034054



### Create tab

- [ ] Create. Промежуточным экраном мигает красная ошибка про баланс https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1211810014



#### Reservation modal window

- [ ] Fix имя у дополнительного Legal документа, чтобы отображать обычное имя объекта (как Terms and Conditionals), а не permlink https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209357020



### Reserved tab


- [ ]  После released, можно оставлять на Reserved, даже если она будет пустая https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209499474





### Release comment

- [ ] Лишняя /@ в ссылке на объект в Reseale комментарии https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1211825499

### Other
- [ ] Вкладки иногда открываются неправильно после резервации и release, такое впечатление что пока не почистишь кеш, они будет продолжать отображать Eligible, хотя есть зарезервированная кампания, или Reserved, хотя кампания была релизнута https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209347820

**Comment by Diana-Cherry-8** [comment]
### Reserved post

- [ ] Fix имя добавленной page (дополнительный legal), чтобы не permlink, а обычное имя объекта в посте о резервации
https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1212862402

### Other
- [ ] Вкладки иногда открываются неправильно после резервации и release, такое впечатление что пока не почистишь кеш, они будет продолжать отображать Eligible, хотя есть зарезервированная кампания, или Reserved, хотя кампания была релизнута https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209347820
- [ ] Было бы хорошо, если бы после деактивации кампания сразу появлялась в нижней таблице (она с верхней пропадает, и только после перезагрузки отображается) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1164034054
- [ ] После released, можно оставлять на Reserved, даже если она будет пустая https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209499474

**Comment by Diana-Cherry-8** [comment]
### Create

- [ ] Добавить возможность добавлять несколько Link to the agreement (сейчас можно только одну страницу).
В модалке резервации они должны быть через запятую: {page1}, {page2}. https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214670581

### Manage
- [x] Fix paid колонку в Manage https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1215053677


### Reservation modal window

- [ ] Fix в модалке резервации и в посте о резервации, с отображением Legal https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214665276



### Reserved post

- [ ] Fix имя добавленной page (дополнительный legal), чтобы не permlink, а обычное имя объекта в посте о резервации
https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1212862402

### Reserved

- [x] В Reserved, у секондари объекта не подтягивается аватар от parent https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214966364
- [x] Лишний отступ в модалке с требованиями (после нажатия на Write review) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214969823
- [x] Название ресторана в тайтле заменилось на "test review" https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214972247
- [x] В модалке требований в самом едиторе, сслыка на ресторан берется не с defaultShowLink (открывается обычная вкладка на ревью) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214975436
- [x] Может чтобы ссылка "the reservation" ввела на пост о резервации (то сейчас просто пустая вкладка Reserved открывается), в модалке когда требование ревью прошло, и последнее согласие пользователя на публикацию https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214986353
- [x] Fix buttons для модалки подтверждения для публикации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214995689
- [ ] Если нажать редактировать ревью, то нельзя будет опубликовать если не прошло 5 минут, хотя обычно нам не нужно ждать 5 минут, если публиковать отредактированный пост https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1215007607



### Other
- [ ] Вкладки иногда открываются неправильно после резервации и release, такое впечатление что пока не почистишь кеш, они будет продолжать отображать Eligible, хотя есть зарезервированная кампания, или Reserved, хотя кампания была релизнута https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209347820
- [ ] Было бы хорошо, если бы после деактивации кампания сразу появлялась в нижней таблице (она с верхней пропадает, и только после перезагрузки отображается) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1164034054
- [ ] После released, можно оставлять на Reserved, даже если она будет пустая https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209499474


### Published review
- [x] undefined в опубликованном ревью https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214999782
- [x] В опубликованном ревью, ссылка у ресторана не на defaultShowLink, а на вкладку Review https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1215012146

**Comment by Diana-Cherry-8** [comment]
### Create

- [ ] Добавить возможность добавлять несколько Link to the agreement (сейчас можно только одну страницу).
В модалке резервации они должны быть через запятую: {page1}, {page2}. https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214670581
- [ ] Отображается только одна прикрепленная page, в режиме просмотра деталей для кампании, хотя с бека приходит 3 (и при создании отображалось 3) (new-way sponsor) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216453166
- [ ] null в matchBots, если сделать дубликат кампании где есть матчботы, то кампания не создастся https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216456444





### Reservation modal window

- [ ] Fix в модалке резервации и в посте о резервации, с отображением Legal https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214665276
- [ ] Много пустого место в строке, рано сделался перенос если много имен матчботов, в модалке резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216463496



### Reservation post

- [ ] Fix имя добавленной page (дополнительный legal), чтобы не permlink, а обычное имя объекта в посте о резервации
https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1212862402
- [ ] Отображается один спонсор, хотя у этой кампании есть добавленные матчботы, в посте о резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216465931


### Reserved

- [ ] Если нажать редактировать ревью, то нельзя будет опубликовать если не прошло 5 минут, хотя обычно нам не нужно ждать 5 минут, если публиковать отредактированный пост https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1215007607
- [ ] Ссылки на undefined объект в модалке проверки требований https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216435628
- [ ] Page not found по нажатию на ссылку "the reservation" в модалке подтверждения публикации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216440785



### Other
- [ ] Вкладки иногда открываются неправильно после резервации и release, такое впечатление что пока не почистишь кеш, они будет продолжать отображать Eligible, хотя есть зарезервированная кампания, или Reserved, хотя кампания была релизнута https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209347820
- [ ] Было бы хорошо, если бы после деактивации кампания сразу появлялась в нижней таблице (она с верхней пропадает, и только после перезагрузки отображается) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1164034054
- [ ] После released, можно оставлять на Reserved, даже если она будет пустая https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209499474


### Published review
- [x] В опубликованном ревью, ссылка у ресторана не на defaultShowLink, а на вкладку Review https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1215012146

**Comment by Diana-Cherry-8** [comment]
**Back-task** https://github.com/Waiviogit/waivio/issues/3429

### Create

- [ ] Добавить возможность добавлять несколько Link to the agreement (сейчас можно только одну страницу).
В модалке резервации они должны быть через запятую: {page1}, {page2}. https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1214670581
- [ ] Отображается только одна прикрепленная page, в режиме просмотра деталей для кампании, хотя с бека приходит 3 (и при создании отображалось 3) (new-way sponsor) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216453166
- [ ] null в matchBots, если сделать дубликат кампании где есть матчботы, то кампания не создастся https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216456444





### Reservation modal window

- [ ] https://github.com/Waiviogit/waivio/issues/4282
- [ ] Много пустого место в строке, рано сделался перенос если много имен матчботов, в модалке резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216463496



### Reservation post

- [ ] Fix имя добавленной page (дополнительный legal), чтобы не permlink, а обычное имя объекта в посте о резервации
https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1212862402
- [ ] Отображается один спонсор, хотя у этой кампании есть добавленные матчботы, в посте о резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216465931


### Reserved

- [ ] Если нажать редактировать ревью, то нельзя будет опубликовать если не прошло 5 минут, хотя обычно нам не нужно ждать 5 минут, если публиковать отредактированный пост https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1215007607
- [ ] Ссылки на undefined объект в модалке проверки требований https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216435628
- [ ] Page not found по нажатию на ссылку "the reservation" в модалке подтверждения публикации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1216440785



### Other
- [ ] Вкладки иногда открываются неправильно после резервации и release, такое впечатление что пока не почистишь кеш, они будет продолжать отображать Eligible, хотя есть зарезервированная кампания, или Reserved, хотя кампания была релизнута https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209347820
- [ ] Было бы хорошо, если бы после деактивации кампания сразу появлялась в нижней таблице (она с верхней пропадает, и только после перезагрузки отображается) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1164034054
- [ ] После released, можно оставлять на Reserved, даже если она будет пустая https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209499474


### Published review
- [x] В опубликованном ревью, ссылка у ресторана не на defaultShowLink, а на вкладку Review https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1215012146
- [ ] В опубликованном ревью карточки объектов не отображаются правильно https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1219334226

**Comment by Diana-Cherry-8** [comment]
**Back-task** https://github.com/Waiviogit/waivio/issues/3429



### Reservation modal window

- [x] https://github.com/Waiviogit/waivio/issues/4282
- [x] Расстояние между слово the и ссылкой на страницу немного больше, чем в других местах, в модалке для резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1222296681



### Reservation post

- [x] Fix имя добавленной page (дополнительный legal), чтобы не permlink, а обычное имя объекта в посте о резервации
https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1212862402
- [x] Подправить блок legal для поста о резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1224031439
- [ ] Пункт "Photo of the receipt (without personal details);" не выглядит как пункт списка в посте о резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1225681985
- [ ] Fix legal блок для поста резервации  https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1225693309


### Reserved

- [ ] Если нажать редактировать ревью, то нельзя будет опубликовать если не прошло 5 минут, хотя обычно нам не нужно ждать 5 минут, если публиковать отредактированный пост https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1215007607

### Published review

- [ ] В опубликованном ревью, ссылка на ресторан ведет не на defaildShowLink, а на обычную https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1220641840



### Other
- [ ] Вкладки иногда открываются неправильно после резервации и release, такое впечатление что пока не почистишь кеш, они будет продолжать отображать Eligible, хотя есть зарезервированная кампания, или Reserved, хотя кампания была релизнута https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209347820
- [x] Было бы хорошо, если бы после деактивации кампания сразу появлялась в нижней таблице (она с верхней пропадает, и только после перезагрузки отображается) https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1164034054
- [ ] https://github.com/Waiviogit/waivio/issues/4288
- [ ] После деактивации кампания не отображается во второй таблице https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1225241352
- [ ] Можно опубликовать ревью которое не соответствует требованием, модалка требований c ошибкой не высветилась
Если у кампании есть требования про Photo of the receipt (without personal details); https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1225639603
- [ ] Если нажать на Write review с вкладки All, то ссылка на primary объект не подтянется https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1225641147

**Comment by Diana-Cherry-8** [comment]
### Reservation post
- [x]  Нет имени ссылки primary объекта в посте о резервации https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1227305005

### Create
- [x] Отображается ошибка с Hive и сообщение про 10 символов при валидации бюджета и реворда.
Лучше чтобы осталась просто одна ошибка если много цифр после точки (больше 8): Reward should be more or equal 0.00000001 WAIV https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1231527262


### Reserved

- [ ] Если нажать редактировать ревью, то нельзя будет опубликовать если не прошло 5 минут, хотя обычно нам не нужно ждать 5 минут, если публиковать отредактированный пост https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1215007607

### Published review

- [ ] В опубликованном ревью, ссылка на ресторан ведет не на defaildShowLink, а на обычную https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1220641840

### Receivable / Payable

- [x] Убрать s в Receivables  и Payables в тайтле на странице таблице во вкладке Receivable и Payable https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1233814507


### Other
- [x] Вкладки иногда открываются неправильно после резервации и release, такое впечатление что пока не почистишь кеш, они будет продолжать отображать Eligible, хотя есть зарезервированная кампания, или Reserved, хотя кампания была релизнута https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1209347820
- [x] Воспроизводиться "Вкладки иногда открываются неправильно после резервации и release" https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1233854313
- [ ] https://github.com/Waiviogit/waivio/issues/4310
- [ ] Падает фронт если нажать на нотификацию (на старых кампаниях)  {user} made a reservation for {campaign} https://github.com/Waiviogit/waivio/issues/4032#issuecomment-1234063342
