### ISSUE TITLE
Add new fields for book type 

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#4277]
**All details here** **Front-task** https://github.com/Waiviogit/waivio/issues/4270

Fields:
- [x] author - search by person all new type author. There may be many authors. https://github.com/Waiviogit/waivio/issues/4280
- [x] ageRange - text field https://github.com/Waiviogit/waivio/issues/4271
- [x] publicationDate - text field https://github.com/Waiviogit/waivio/issues/4272
- [x] language - text field https://github.com/Waiviogit/waivio/issues/4273
- [x] publisher - search by business objects https://github.com/Waiviogit/waivio/issues/4274
- [x] weight - 1 field and 1 dropdown https://github.com/Waiviogit/waivio/issues/4275
- [x] dimensions - 3 fields and 1 dropdown https://github.com/Waiviogit/waivio/issues/4276
- [x] groupId https://github.com/Waiviogit/waivio/issues/4286
- [x] printLenght -> printLength - number + word (pages) #4322 

Options:
- [x] format https://github.com/Waiviogit/waivio/issues/4285

**Comment by Waiviogit** [comment]
https://github.com/Waiviogit/objects-bot/blob/dev/docs/objectFields.md

**Comment by Diana-Cherry-8** [comment]
**CLOSE**
