### ISSUE TITLE
Editor checklist

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6538]
Editor
- [ ] #3977 same #5960

Copy-past
- [ ] #4155
- [ ] #4111
- [ ] #6211
- [ ] [Enter (adding a blank line) is not always pressed when inserting text with pictures](https://github.com/Waiviogit/waivio/issues/5951#issuecomment-1742815375)
- [ ] [Copied text from the GPT chat (or any place where there are lists) does not distinguish between items and sub-items](https://github.com/Waiviogit/waivio/issues/5951#issuecomment-1742827170) 

Images
- [ ] #6226
- [ ] [The picture is deleted if you press backspace](https://github.com/Waiviogit/waivio/issues/5951#issuecomment-1742838368)

Table
- [ ] #4353
- [ ] #4094
- [ ] #5505
- [ ] #4118
- [ ] #6389

Page editor
- [ ] #3259

Mobile
- [ ] #4363
- [ ] #4147 (general task)

### Small fixes improvements
- [ ] #6537
- [ ] #6218
- [ ] #4248 (straighten icons, change one icon)

**Comment by Diana-Cherry-8** [comment]
## DONE

### Editor
- [x] #3977 
- [x]  #4084
- [x] #5960
- [x] #6699
- [x]  #4363
- [x]  #4091
- [x] #7342
- [x] #7324

### Guest
- [x] #7323
- [x] #7353


### Images
- [x] #6226
- [x] [The picture is deleted if you press backspace](https://github.com/Waiviogit/waivio/issues/5951#issuecomment-1742838368)


### Table
- [x] #4118
- [x] [The Enter doesn't function to add a new line in the table cell](https://github.com/Waiviogit/waivio/issues/5951#issuecomment-2012330903)
- [x] table [If you add a table within a table, the result is strange](https://github.com/Waiviogit/waivio/issues/5951#issuecomment-2012348168)


### Mobile
- [x] #4363


### Profile
- [x] #6712 
- [x] #7355

### Small fixes improvements
- [x] #6537
- [x] #6218
- [x] #4248 (straighten icons, change one icon)
- [x]  [The cursor is being thrown, and the plus button is being moved upwards. If you select text -> make it into a list -> the cursor is moved to the 1st line.](https://github.com/Waiviogit/waivio/issues/5951#issuecomment-2012265667)
- [x] [Reduce the spacing between lines for code insertion using the plus button -> Code.](https://github.com/Waiviogit/waivio/issues/5951#issuecomment-2012277652)
- [x] The editor menu is displayed partially and with scrolling inside the post.
[#6218](https://github.com/Waiviogit/waivio/issues/6218)
- [x] [Курсор вылетает, после того как сделать ссылку.](https://github.com/Waiviogit/waivio/issues/5951#issuecomment-2499856442)

**Comment by Diana-Cherry-8** [comment]
## DONE
### Table
- [x] #6389
- [x] [Таблица не удалиться если она самая 1я в редакторе.](https://github.com/Waiviogit/waivio/issues/4118#issuecomment-2772412224)
- [x] #7420
- [x] #7426
- [x] #7436
- [x] #7440
- [x] #7451

### New
- [ ] #7393 
- [x] #7462
