### ISSUE TITLE
SEO issues summary

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6583]
Main domain

- [ ] waivio loader на full cached version, хотя в текстовой версии и source все правильно [Details](https://github.com/Waiviogit/waivio/issues/6084#issuecomment-1898325772)

List

- [ ] Fix canonical для ссылки без "#" для листов на сайтах (checklist) [Details](https://github.com/Waiviogit/waivio/issues/6084#issuecomment-2029816273)
- [ ] Fix открытие страницы если ссылка без "#" для листов на сайтах (checklist) [Details](https://github.com/Waiviogit/waivio/issues/6084#issuecomment-2029820516)

Product

- [ ] Fix "pic" alt текст для картинок preview галерее на странице продукта на сайтах [Details](https://github.com/Waiviogit/waivio/issues/6548#issuecomment-2019837511)
- [ ] Нет постов на странице конкретного продукта в raw html (в основном посты есть) [Details](https://github.com/Waiviogit/waivio/issues/6084#issuecomment-1941242196)
- [ ] Related/Similar/Add-ons блоки не попадают в raw html на странице продукта на сайтах [Details](https://github.com/Waiviogit/waivio/issues/6084#issuecomment-1940840491)
- [ ] waivio loader на full cached version, хотя в текстовой версии и source все правильно, то что относиться к сайту, на странице продукта [Details](https://github.com/Waiviogit/waivio/issues/6084#issuecomment-2031274650)

Book 
- [ ] publicationDate "Invalid date" в raw html https://github.com/Waiviogit/waivio/issues/6084#issuecomment-2042383144

Business / Restaurant
- [ ] Нет постов в raw html https://github.com/Waiviogit/waivio/issues/6084#issuecomment-2039647774
- [ ] Нет списка экспертов в raw html https://github.com/Waiviogit/waivio/issues/6084#issuecomment-2039644705

Profile
- [ ] Expertise блок для пользователя показывается только если пользователь авторизован, на Posts, Favorites, Followers, Expertise страницах. [Details](https://github.com/Waiviogit/waivio/issues/6084#issuecomment-2044243760)           

Newsfeed
- [ ] Урезать meta description, если оно слишком большое [Details](https://github.com/Waiviogit/waivio/issues/6548#issuecomment-2019837076)
- [ ] Убрать кнопку-линку на пост, вместо этого подправить структуру title поста, чтобы было ссылкой https://github.com/Waiviogit/waivio/issues/6003#issuecomment-1941289354
- [ ] Нет постов в raw html, если newsfeed стоит 1‑й страницей, на главном домене [Details](https://github.com/Waiviogit/waivio/issues/6003#issuecomment-2024780129)
